name: iutableso
description: A restaurant comparison app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0  # For Supabase integration
  http: ^1.1.0            # For additional HTTP requests if needed
  flutter_secure_storage: ^9.0.0  # For storing auth tokens
  provider: ^6.0.0        
  flutter_map: ^6.0.0     
  latlong2: ^0.9.0        

dev_dependencies:
  flutter_test:
    sdk: flutter